package com.rocket.myshop.mapper;

import java.util.List;
import java.util.Map;

import com.rocket.myshop.domain.Item;
import com.rocket.myshop.dto.ItemDto;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Item record);
    
    int getCount(Map<String, Object> params);

	List<ItemDto> listItem(Map<String, Object> params);
}