package com.rocket.myshop.mapper;

import java.util.List;
import java.util.Map;

import com.rocket.myshop.domain.ItemBrand;
import com.rocket.myshop.dto.ItemBrandDto;

public interface ItemBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    int insert(ItemBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    int insertSelective(ItemBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    ItemBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemBrand record);

	int getCount(Map<String, Object> params);

	List<ItemBrandDto> listItemBrand(Map<String, Object> params);
}