package com.rocket.myshop.mapper;

import com.rocket.myshop.domain.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);
}