package com.rocket.myshop.mapper;

import com.rocket.myshop.domain.ItemCategory;

public interface ItemCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    int insert(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    int insertSelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    ItemCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_item_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemCategory record);
}