package com.rocket.myshop.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.id_
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.title_
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.sell_point_
     *
     * @mbg.generated
     */
    private String sellPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.price_
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.num_
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.barcode_
     *
     * @mbg.generated
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.img_logo_
     *
     * @mbg.generated
     */
    private String imgLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.status_
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.create_time_
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.update_time_
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.seller_id_
     *
     * @mbg.generated
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_category_name_
     *
     * @mbg.generated
     */
    private String itemCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_brand_name_
     *
     * @mbg.generated
     */
    private String itemBrandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.sale_clients_
     *
     * @mbg.generated
     */
    private String saleClients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.id_
     *
     * @return the value of shop_item.id_
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.id_
     *
     * @param id the value for shop_item.id_
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.title_
     *
     * @return the value of shop_item.title_
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.title_
     *
     * @param title the value for shop_item.title_
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.sell_point_
     *
     * @return the value of shop_item.sell_point_
     *
     * @mbg.generated
     */
    public String getSellPoint() {
        return sellPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.sell_point_
     *
     * @param sellPoint the value for shop_item.sell_point_
     *
     * @mbg.generated
     */
    public void setSellPoint(String sellPoint) {
        this.sellPoint = sellPoint == null ? null : sellPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.price_
     *
     * @return the value of shop_item.price_
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.price_
     *
     * @param price the value for shop_item.price_
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.num_
     *
     * @return the value of shop_item.num_
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.num_
     *
     * @param num the value for shop_item.num_
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.barcode_
     *
     * @return the value of shop_item.barcode_
     *
     * @mbg.generated
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.barcode_
     *
     * @param barcode the value for shop_item.barcode_
     *
     * @mbg.generated
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.img_logo_
     *
     * @return the value of shop_item.img_logo_
     *
     * @mbg.generated
     */
    public String getImgLogo() {
        return imgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.img_logo_
     *
     * @param imgLogo the value for shop_item.img_logo_
     *
     * @mbg.generated
     */
    public void setImgLogo(String imgLogo) {
        this.imgLogo = imgLogo == null ? null : imgLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.status_
     *
     * @return the value of shop_item.status_
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.status_
     *
     * @param status the value for shop_item.status_
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.create_time_
     *
     * @return the value of shop_item.create_time_
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.create_time_
     *
     * @param createTime the value for shop_item.create_time_
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.update_time_
     *
     * @return the value of shop_item.update_time_
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.update_time_
     *
     * @param updateTime the value for shop_item.update_time_
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.seller_id_
     *
     * @return the value of shop_item.seller_id_
     *
     * @mbg.generated
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.seller_id_
     *
     * @param sellerId the value for shop_item.seller_id_
     *
     * @mbg.generated
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_category_name_
     *
     * @return the value of shop_item.item_category_name_
     *
     * @mbg.generated
     */
    public String getItemCategoryName() {
        return itemCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_category_name_
     *
     * @param itemCategoryName the value for shop_item.item_category_name_
     *
     * @mbg.generated
     */
    public void setItemCategoryName(String itemCategoryName) {
        this.itemCategoryName = itemCategoryName == null ? null : itemCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_brand_name_
     *
     * @return the value of shop_item.item_brand_name_
     *
     * @mbg.generated
     */
    public String getItemBrandName() {
        return itemBrandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_brand_name_
     *
     * @param itemBrandName the value for shop_item.item_brand_name_
     *
     * @mbg.generated
     */
    public void setItemBrandName(String itemBrandName) {
        this.itemBrandName = itemBrandName == null ? null : itemBrandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.sale_clients_
     *
     * @return the value of shop_item.sale_clients_
     *
     * @mbg.generated
     */
    public String getSaleClients() {
        return saleClients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.sale_clients_
     *
     * @param saleClients the value for shop_item.sale_clients_
     *
     * @mbg.generated
     */
    public void setSaleClients(String saleClients) {
        this.saleClients = saleClients == null ? null : saleClients.trim();
    }
}